/*
DCSA Components

Common components for DCSA APIs and Domains. This Domain maintains common SimpleTypes, Headers and parameters used throughout all DCSA APIs and Domains.  For a history of changes in this domain - please check [GitHub](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/domain/dcsa#v202). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

API version: 2.0.2
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// SealSource The source of the seal, namely who has affixed the seal. This attribute links to the Seal Source ID defined in the Seal Source reference data entity. - CAR (Carrier) - SHI (Shipper) - PHY (Phytosanitary) - VET (Veterinary) - CUS (Customs)
type SealSource string

// List of sealSource
const (
	CAR SealSource = "CAR"
	SHI SealSource = "SHI"
	PHY SealSource = "PHY"
	VET SealSource = "VET"
	CUS SealSource = "CUS"
)

// All allowed values of SealSource enum
var AllowedSealSourceEnumValues = []SealSource{
	"CAR",
	"SHI",
	"PHY",
	"VET",
	"CUS",
}

func (v *SealSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SealSource(value)
	for _, existing := range AllowedSealSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SealSource", value)
}

// NewSealSourceFromValue returns a pointer to a valid SealSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSealSourceFromValue(v string) (*SealSource, error) {
	ev := SealSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SealSource: valid values are %v", v, AllowedSealSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SealSource) IsValid() bool {
	for _, existing := range AllowedSealSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to sealSource value
func (v SealSource) Ptr() *SealSource {
	return &v
}

type NullableSealSource struct {
	value *SealSource
	isSet bool
}

func (v NullableSealSource) Get() *SealSource {
	return v.value
}

func (v *NullableSealSource) Set(val *SealSource) {
	v.value = val
	v.isSet = true
}

func (v NullableSealSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSealSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealSource(val *SealSource) *NullableSealSource {
	return &NullableSealSource{value: val, isSet: true}
}

func (v NullableSealSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
