/*
DCSA Components

Common components for DCSA APIs and Domains. This Domain maintains common SimpleTypes, Headers and parameters used throughout all DCSA APIs and Domains.  For a history of changes in this domain - please check [GitHub](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/domain/dcsa#v202). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

API version: 2.0.2
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// DimensionUnit The unit of measure which can be expressed in - MTR (Meter) - FOT (Foot)
type DimensionUnit string

// List of dimensionUnit
const (
	DimensionUnitMeter DimensionUnit = "MTR"
	DimensionUnitFoot  DimensionUnit = "FOT"
)

// All allowed values of DimensionUnit enum
var AllowedDimensionUnitEnumValues = []DimensionUnit{
	DimensionUnitMeter,
	DimensionUnitFoot,
}

func (v *DimensionUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DimensionUnit(value)
	for _, existing := range AllowedDimensionUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DimensionUnit", value)
}

// NewDimensionUnitFromValue returns a pointer to a valid DimensionUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDimensionUnitFromValue(v string) (*DimensionUnit, error) {
	ev := DimensionUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DimensionUnit: valid values are %v", v, AllowedDimensionUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DimensionUnit) IsValid() bool {
	for _, existing := range AllowedDimensionUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to dimensionUnit value
func (v DimensionUnit) Ptr() *DimensionUnit {
	return &v
}

type NullableDimensionUnit struct {
	value *DimensionUnit
	isSet bool
}

func (v NullableDimensionUnit) Get() *DimensionUnit {
	return v.value
}

func (v *NullableDimensionUnit) Set(val *DimensionUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableDimensionUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableDimensionUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDimensionUnit(val *DimensionUnit) *NullableDimensionUnit {
	return &NullableDimensionUnit{value: val, isSet: true}
}

func (v NullableDimensionUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDimensionUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
