/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// ModeOfTransport The mode of transport as defined by DCSA.
type ModeOfTransport string

// List of modeOfTransport
const (
	ModeOfTransportVessel ModeOfTransport = "VESSEL"
	ModeOfTransportRail   ModeOfTransport = "RAIL"
	ModeOfTransportTruck  ModeOfTransport = "TRUCK"
	ModeOfTransportBarge  ModeOfTransport = "BARGE"
)

// All allowed values of ModeOfTransport enum
var AllowedModeOfTransportEnumValues = []ModeOfTransport{
	"VESSEL",
	"RAIL",
	"TRUCK",
	"BARGE",
}

func (v *ModeOfTransport) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModeOfTransport(value)
	for _, existing := range AllowedModeOfTransportEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModeOfTransport", value)
}

// NewModeOfTransportFromValue returns a pointer to a valid ModeOfTransport
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModeOfTransportFromValue(v string) (*ModeOfTransport, error) {
	ev := ModeOfTransport(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModeOfTransport: valid values are %v", v, AllowedModeOfTransportEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModeOfTransport) IsValid() bool {
	for _, existing := range AllowedModeOfTransportEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to modeOfTransport value
func (v ModeOfTransport) Ptr() *ModeOfTransport {
	return &v
}

type NullableModeOfTransport struct {
	value *ModeOfTransport
	isSet bool
}

func (v NullableModeOfTransport) Get() *ModeOfTransport {
	return v.value
}

func (v *NullableModeOfTransport) Set(val *ModeOfTransport) {
	v.value = val
	v.isSet = true
}

func (v NullableModeOfTransport) IsSet() bool {
	return v.isSet
}

func (v *NullableModeOfTransport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModeOfTransport(val *ModeOfTransport) *NullableModeOfTransport {
	return &NullableModeOfTransport{value: val, isSet: true}
}

func (v NullableModeOfTransport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModeOfTransport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
