/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// WeightUnit The unit of measure which can be expressed in imperial or metric terms
type WeightUnit string

// List of weightUnit
const (
	WeightUnitMetricTon   WeightUnit = "KGM"
	WeightUnitImperialTon WeightUnit = "LBR"
)

// All allowed values of WeightUnit enum
var AllowedWeightUnitEnumValues = []WeightUnit{
	WeightUnitMetricTon,
	WeightUnitImperialTon,
}

func (v *WeightUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WeightUnit(value)
	for _, existing := range AllowedWeightUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WeightUnit", value)
}

// NewWeightUnitFromValue returns a pointer to a valid WeightUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWeightUnitFromValue(v string) (*WeightUnit, error) {
	ev := WeightUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WeightUnit: valid values are %v", v, AllowedWeightUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WeightUnit) IsValid() bool {
	for _, existing := range AllowedWeightUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to weightUnit value
func (v WeightUnit) Ptr() *WeightUnit {
	return &v
}

type NullableWeightUnit struct {
	value *WeightUnit
	isSet bool
}

func (v NullableWeightUnit) Get() *WeightUnit {
	return v.value
}

func (v *NullableWeightUnit) Set(val *WeightUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableWeightUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableWeightUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWeightUnit(val *WeightUnit) *NullableWeightUnit {
	return &NullableWeightUnit{value: val, isSet: true}
}

func (v NullableWeightUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWeightUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
