/*
DCSA Components

Common components for DCSA APIs and Domains. This Domain maintains common SimpleTypes, Headers and parameters used throughout all DCSA APIs and Domains.  For a history of changes in this domain - please check [GitHub](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/domain/dcsa#v202). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

API version: 2.0.2
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// CommunicationChannelCode Specifying which communication channel is to be used for this booking e.g. - EI (EDI transmission) - EM (Email) - AO (API)
type CommunicationChannelCode string

// List of communicationChannelCode
const (
	CommunicationChannelEDI   CommunicationChannelCode = "EI"
	CommunicationChannelEmail CommunicationChannelCode = "EM"
	CommunicationChannelAPI   CommunicationChannelCode = "AO"
)

// All allowed values of CommunicationChannelCode enum
var AllowedCommunicationChannelCodeEnumValues = []CommunicationChannelCode{
	CommunicationChannelEDI,
	CommunicationChannelEmail,
	CommunicationChannelAPI,
}

func (v *CommunicationChannelCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CommunicationChannelCode(value)
	for _, existing := range AllowedCommunicationChannelCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CommunicationChannelCode", value)
}

// NewCommunicationChannelCodeFromValue returns a pointer to a valid CommunicationChannelCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCommunicationChannelCodeFromValue(v string) (*CommunicationChannelCode, error) {
	ev := CommunicationChannelCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CommunicationChannelCode: valid values are %v", v, AllowedCommunicationChannelCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CommunicationChannelCode) IsValid() bool {
	for _, existing := range AllowedCommunicationChannelCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to communicationChannelCode value
func (v CommunicationChannelCode) Ptr() *CommunicationChannelCode {
	return &v
}

type NullableCommunicationChannelCode struct {
	value *CommunicationChannelCode
	isSet bool
}

func (v NullableCommunicationChannelCode) Get() *CommunicationChannelCode {
	return v.value
}

func (v *NullableCommunicationChannelCode) Set(val *CommunicationChannelCode) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunicationChannelCode) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunicationChannelCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunicationChannelCode(val *CommunicationChannelCode) *NullableCommunicationChannelCode {
	return &NullableCommunicationChannelCode{value: val, isSet: true}
}

func (v NullableCommunicationChannelCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunicationChannelCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
