/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// TemperatureUnit Celsius (CEL) or Fahrenheit (FAH).
type TemperatureUnit string

// List of temperatureUnit
const (
	TemperatureUnitCelsius    TemperatureUnit = "CEL"
	TemperatureUnitFahrenheit TemperatureUnit = "FAH"
)

// All allowed values of TemperatureUnit enum
var AllowedTemperatureUnitEnumValues = []TemperatureUnit{
	TemperatureUnitCelsius,
	TemperatureUnitFahrenheit,
}

func (v *TemperatureUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TemperatureUnit(value)
	for _, existing := range AllowedTemperatureUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TemperatureUnit", value)
}

// NewTemperatureUnitFromValue returns a pointer to a valid TemperatureUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTemperatureUnitFromValue(v string) (*TemperatureUnit, error) {
	ev := TemperatureUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TemperatureUnit: valid values are %v", v, AllowedTemperatureUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TemperatureUnit) IsValid() bool {
	for _, existing := range AllowedTemperatureUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to temperatureUnit value
func (v TemperatureUnit) Ptr() *TemperatureUnit {
	return &v
}

type NullableTemperatureUnit struct {
	value *TemperatureUnit
	isSet bool
}

func (v NullableTemperatureUnit) Get() *TemperatureUnit {
	return v.value
}

func (v *NullableTemperatureUnit) Set(val *TemperatureUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableTemperatureUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableTemperatureUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemperatureUnit(val *TemperatureUnit) *NullableTemperatureUnit {
	return &NullableTemperatureUnit{value: val, isSet: true}
}

func (v NullableTemperatureUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemperatureUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
