/*
DCSA Components

Common components for DCSA APIs and Domains. This Domain maintains common SimpleTypes, Headers and parameters used throughout all DCSA APIs and Domains.  For a history of changes in this domain - please check [GitHub](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/domain/dcsa#v202). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

API version: 2.0.2
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// PreCarriageUnderShippersResponsibility Mode of transportation for pre-carriage (e.g., truck, barge, rail), under shipper&apos;s responsibility
type PreCarriageUnderShippersResponsibility string

// List of preCarriageUnderShippersResponsibility
const (
	VESSEL PreCarriageUnderShippersResponsibility = "VESSEL"
	RAIL   PreCarriageUnderShippersResponsibility = "RAIL"
	TRUCK  PreCarriageUnderShippersResponsibility = "TRUCK"
	BARGE  PreCarriageUnderShippersResponsibility = "BARGE"
)

// All allowed values of PreCarriageUnderShippersResponsibility enum
var AllowedPreCarriageUnderShippersResponsibilityEnumValues = []PreCarriageUnderShippersResponsibility{
	"VESSEL",
	"RAIL",
	"TRUCK",
	"BARGE",
}

func (v *PreCarriageUnderShippersResponsibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PreCarriageUnderShippersResponsibility(value)
	for _, existing := range AllowedPreCarriageUnderShippersResponsibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PreCarriageUnderShippersResponsibility", value)
}

// NewPreCarriageUnderShippersResponsibilityFromValue returns a pointer to a valid PreCarriageUnderShippersResponsibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPreCarriageUnderShippersResponsibilityFromValue(v string) (*PreCarriageUnderShippersResponsibility, error) {
	ev := PreCarriageUnderShippersResponsibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PreCarriageUnderShippersResponsibility: valid values are %v", v, AllowedPreCarriageUnderShippersResponsibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PreCarriageUnderShippersResponsibility) IsValid() bool {
	for _, existing := range AllowedPreCarriageUnderShippersResponsibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to preCarriageUnderShippersResponsibility value
func (v PreCarriageUnderShippersResponsibility) Ptr() *PreCarriageUnderShippersResponsibility {
	return &v
}

type NullablePreCarriageUnderShippersResponsibility struct {
	value *PreCarriageUnderShippersResponsibility
	isSet bool
}

func (v NullablePreCarriageUnderShippersResponsibility) Get() *PreCarriageUnderShippersResponsibility {
	return v.value
}

func (v *NullablePreCarriageUnderShippersResponsibility) Set(val *PreCarriageUnderShippersResponsibility) {
	v.value = val
	v.isSet = true
}

func (v NullablePreCarriageUnderShippersResponsibility) IsSet() bool {
	return v.isSet
}

func (v *NullablePreCarriageUnderShippersResponsibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreCarriageUnderShippersResponsibility(val *PreCarriageUnderShippersResponsibility) *NullablePreCarriageUnderShippersResponsibility {
	return &NullablePreCarriageUnderShippersResponsibility{value: val, isSet: true}
}

func (v NullablePreCarriageUnderShippersResponsibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreCarriageUnderShippersResponsibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
