/*
DCSA Components

Common components for DCSA APIs and Domains. This Domain maintains common SimpleTypes, Headers and parameters used throughout all DCSA APIs and Domains.  For a history of changes in this domain - please check [GitHub](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/domain/dcsa#v202). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

API version: 2.0.2
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

// FacilityTypeCodeOPR A specialized version of the facilityCode to be used in Operations events. The code to identify the specific type of facility.
// - PBPL (Pilot boarding place)
// - BRTH (Berth)
// - ANCH (Anchorage Location)
type FacilityTypeCodeOPR string

// List of facilityTypeCodeOPR
const (
	FacilityTypeCodeOpBoarding  FacilityTypeCodeOPR = "PBPL"
	FacilityTypeCodeOpBerth     FacilityTypeCodeOPR = "BRTH"
	FacilityTypeCodeOpAnchorage FacilityTypeCodeOPR = "ANCH"
)

// All allowed values of FacilityTypeCodeOPR enum
var AllowedFacilityTypeCodeOPREnumValues = []FacilityTypeCodeOPR{
	FacilityTypeCodeOpBoarding,
	FacilityTypeCodeOpBerth,
	FacilityTypeCodeOpAnchorage,
}

func (v *FacilityTypeCodeOPR) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FacilityTypeCodeOPR(value)
	for _, existing := range AllowedFacilityTypeCodeOPREnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FacilityTypeCodeOPR", value)
}

// NewFacilityTypeCodeOPRFromValue returns a pointer to a valid FacilityTypeCodeOPR
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFacilityTypeCodeOPRFromValue(v string) (*FacilityTypeCodeOPR, error) {
	ev := FacilityTypeCodeOPR(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FacilityTypeCodeOPR: valid values are %v", v, AllowedFacilityTypeCodeOPREnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FacilityTypeCodeOPR) IsValid() bool {
	for _, existing := range AllowedFacilityTypeCodeOPREnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to facilityTypeCodeOPR value
func (v FacilityTypeCodeOPR) Ptr() *FacilityTypeCodeOPR {
	return &v
}

type NullableFacilityTypeCodeOPR struct {
	value *FacilityTypeCodeOPR
	isSet bool
}

func (v NullableFacilityTypeCodeOPR) Get() *FacilityTypeCodeOPR {
	return v.value
}

func (v *NullableFacilityTypeCodeOPR) Set(val *FacilityTypeCodeOPR) {
	v.value = val
	v.isSet = true
}

func (v NullableFacilityTypeCodeOPR) IsSet() bool {
	return v.isSet
}

func (v *NullableFacilityTypeCodeOPR) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacilityTypeCodeOPR(val *FacilityTypeCodeOPR) *NullableFacilityTypeCodeOPR {
	return &NullableFacilityTypeCodeOPR{value: val, isSet: true}
}

func (v NullableFacilityTypeCodeOPR) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacilityTypeCodeOPR) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
