/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bol

import (
	"encoding/json"
	"fmt"
)

// IssuerCodeListProvider The provider used for identifying the issuer Code
type IssuerCodeListProvider string

// List of issuerCodeListProvider
const (
	IssuerCodeListProviderSMDG  IssuerCodeListProvider = "SMDG"
	IssuerCodeListProviderNMFTA IssuerCodeListProvider = "NMFTA"
)

// All allowed values of IssuerCodeListProvider enum
var AllowedIssuerCodeListProviderEnumValues = []IssuerCodeListProvider{
	IssuerCodeListProviderSMDG,
	IssuerCodeListProviderNMFTA,
}

func (v *IssuerCodeListProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IssuerCodeListProvider(value)
	for _, existing := range AllowedIssuerCodeListProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IssuerCodeListProvider", value)
}

// NewIssuerCodeListProviderFromValue returns a pointer to a valid IssuerCodeListProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIssuerCodeListProviderFromValue(v string) (*IssuerCodeListProvider, error) {
	ev := IssuerCodeListProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IssuerCodeListProvider: valid values are %v", v, AllowedIssuerCodeListProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IssuerCodeListProvider) IsValid() bool {
	for _, existing := range AllowedIssuerCodeListProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to issuerCodeListProvider value
func (v IssuerCodeListProvider) Ptr() *IssuerCodeListProvider {
	return &v
}

type NullableIssuerCodeListProvider struct {
	value *IssuerCodeListProvider
	isSet bool
}

func (v NullableIssuerCodeListProvider) Get() *IssuerCodeListProvider {
	return v.value
}

func (v *NullableIssuerCodeListProvider) Set(val *IssuerCodeListProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerCodeListProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerCodeListProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerCodeListProvider(val *IssuerCodeListProvider) *NullableIssuerCodeListProvider {
	return &NullableIssuerCodeListProvider{value: val, isSet: true}
}

func (v NullableIssuerCodeListProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerCodeListProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
