/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bol

import (
	"encoding/json"
	"fmt"
)

// DocumentTypeCode The code to identify the type of information documentID points to. Can be one of the following values - BKG (Booking) - SHI (Shipping Instruction) - SRM (Shipment Release Message) - TRD (Transport Document) - ARN (Arrival Notice)
type DocumentTypeCode string

// List of documentTypeCode
const (
	DocumentTypeBooking                DocumentTypeCode = "BKG"
	DocumentTypeShippingInstruction    DocumentTypeCode = "SHI"
	DocumentTypeShippingReleaseMessage DocumentTypeCode = "SRM"
	DocumentTypeTransport              DocumentTypeCode = "TRD"
	DocumentTypeArrivalNotice          DocumentTypeCode = "ARN"
)

// All allowed values of DocumentTypeCode enum
var AllowedDocumentTypeCodeEnumValues = []DocumentTypeCode{
	DocumentTypeBooking,
	DocumentTypeShippingInstruction,
	DocumentTypeShippingReleaseMessage,
	DocumentTypeTransport,
	DocumentTypeArrivalNotice,
}

func (v *DocumentTypeCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DocumentTypeCode(value)
	for _, existing := range AllowedDocumentTypeCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DocumentTypeCode", value)
}

// NewDocumentTypeCodeFromValue returns a pointer to a valid DocumentTypeCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDocumentTypeCodeFromValue(v string) (*DocumentTypeCode, error) {
	ev := DocumentTypeCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DocumentTypeCode: valid values are %v", v, AllowedDocumentTypeCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DocumentTypeCode) IsValid() bool {
	for _, existing := range AllowedDocumentTypeCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to documentTypeCode value
func (v DocumentTypeCode) Ptr() *DocumentTypeCode {
	return &v
}

type NullableDocumentTypeCode struct {
	value *DocumentTypeCode
	isSet bool
}

func (v NullableDocumentTypeCode) Get() *DocumentTypeCode {
	return v.value
}

func (v *NullableDocumentTypeCode) Set(val *DocumentTypeCode) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentTypeCode) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentTypeCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentTypeCode(val *DocumentTypeCode) *NullableDocumentTypeCode {
	return &NullableDocumentTypeCode{value: val, isSet: true}
}

func (v NullableDocumentTypeCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentTypeCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
