/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bol

import (
	"encoding/json"
)

// CargoItems struct for CargoItems
type CargoItems struct {
	CargoItems []CargoItem `json:"cargoItems,omitempty"`
}

// NewCargoItems instantiates a new CargoItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCargoItems() *CargoItems {
	this := CargoItems{}
	return &this
}

// NewCargoItemsWithDefaults instantiates a new CargoItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCargoItemsWithDefaults() *CargoItems {
	this := CargoItems{}
	return &this
}

// GetCargoItems returns the CargoItems field value if set, zero value otherwise.
func (o *CargoItems) GetCargoItems() []CargoItem {
	if o == nil || o.CargoItems == nil {
		var ret []CargoItem
		return ret
	}
	return o.CargoItems
}

// GetCargoItemsOk returns a tuple with the CargoItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CargoItems) GetCargoItemsOk() ([]CargoItem, bool) {
	if o == nil || o.CargoItems == nil {
		return nil, false
	}
	return o.CargoItems, true
}

// HasCargoItems returns a boolean if a field has been set.
func (o *CargoItems) HasCargoItems() bool {
	if o != nil && o.CargoItems != nil {
		return true
	}

	return false
}

// SetCargoItems gets a reference to the given []CargoItem and assigns it to the CargoItems field.
func (o *CargoItems) SetCargoItems(v []CargoItem) {
	o.CargoItems = v
}

func (o CargoItems) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CargoItems != nil {
		toSerialize["cargoItems"] = o.CargoItems
	}
	return json.Marshal(toSerialize)
}

type NullableCargoItems struct {
	value *CargoItems
	isSet bool
}

func (v NullableCargoItems) Get() *CargoItems {
	return v.value
}

func (v *NullableCargoItems) Set(val *CargoItems) {
	v.value = val
	v.isSet = true
}

func (v NullableCargoItems) IsSet() bool {
	return v.isSet
}

func (v *NullableCargoItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCargoItems(val *CargoItems) *NullableCargoItems {
	return &NullableCargoItems{value: val, isSet: true}
}

func (v NullableCargoItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCargoItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
