/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bol

import (
	"encoding/json"
)

// ShipmentLocation maps the relationship between Shipment and Location, e.g., the place of receipt and the places of delivery for a specific shipment.
type ShipmentLocation struct {
	Location *Location `json:"location,omitempty"`
	// The address of the party to be displayed on the transport document.
	DisplayedName *string      `json:"displayedName,omitempty"`
	LocationType  LocationType `json:"locationType"`
}

// NewShipmentLocation instantiates a new ShipmentLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentLocation(locationType LocationType) *ShipmentLocation {
	this := ShipmentLocation{}
	this.LocationType = locationType
	return &this
}

// NewShipmentLocationWithDefaults instantiates a new ShipmentLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentLocationWithDefaults() *ShipmentLocation {
	this := ShipmentLocation{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ShipmentLocation) GetLocation() Location {
	if o == nil || o.Location == nil {
		var ret Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentLocation) GetLocationOk() (*Location, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ShipmentLocation) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given Location and assigns it to the Location field.
func (o *ShipmentLocation) SetLocation(v Location) {
	o.Location = &v
}

// GetDisplayedName returns the DisplayedName field value if set, zero value otherwise.
func (o *ShipmentLocation) GetDisplayedName() string {
	if o == nil || o.DisplayedName == nil {
		var ret string
		return ret
	}
	return *o.DisplayedName
}

// GetDisplayedNameOk returns a tuple with the DisplayedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentLocation) GetDisplayedNameOk() (*string, bool) {
	if o == nil || o.DisplayedName == nil {
		return nil, false
	}
	return o.DisplayedName, true
}

// HasDisplayedName returns a boolean if a field has been set.
func (o *ShipmentLocation) HasDisplayedName() bool {
	if o != nil && o.DisplayedName != nil {
		return true
	}

	return false
}

// SetDisplayedName gets a reference to the given string and assigns it to the DisplayedName field.
func (o *ShipmentLocation) SetDisplayedName(v string) {
	o.DisplayedName = &v
}

// GetLocationType returns the LocationType field value
func (o *ShipmentLocation) GetLocationType() LocationType {
	if o == nil {
		var ret LocationType
		return ret
	}

	return o.LocationType
}

// GetLocationTypeOk returns a tuple with the LocationType field value
// and a boolean to check if the value has been set.
func (o *ShipmentLocation) GetLocationTypeOk() (*LocationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationType, true
}

// SetLocationType sets field value
func (o *ShipmentLocation) SetLocationType(v LocationType) {
	o.LocationType = v
}

func (o ShipmentLocation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	if o.DisplayedName != nil {
		toSerialize["displayedName"] = o.DisplayedName
	}
	if true {
		toSerialize["locationType"] = o.LocationType
	}
	return json.Marshal(toSerialize)
}

type NullableShipmentLocation struct {
	value *ShipmentLocation
	isSet bool
}

func (v NullableShipmentLocation) Get() *ShipmentLocation {
	return v.value
}

func (v *NullableShipmentLocation) Set(val *ShipmentLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentLocation(val *ShipmentLocation) *NullableShipmentLocation {
	return &NullableShipmentLocation{value: val, isSet: true}
}

func (v NullableShipmentLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
