/*
DCSA OpenAPI specification for Electronic Bill of Lading

API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf'>Information Model v3.0</a>  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the <a href='https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB'>DCSA Documentation Event Hub</a> in order to use the push model. Here events are pushed as they occur.

API version: 1.0.0
Contact: info@dcsa.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bol

import (
	"encoding/json"
	"fmt"
)

// PreCarriageUnderShippersResponsibility Mode of transportation for pre-carriage (e.g., truck, barge, rail), under shipper&apos;s responsibility
type PreCarriageUnderShippersResponsibility string

// List of preCarriageUnderShippersResponsibility
const (
	VESSEL PreCarriageUnderShippersResponsibility = "VESSEL"
	RAIL   PreCarriageUnderShippersResponsibility = "RAIL"
	TRUCK  PreCarriageUnderShippersResponsibility = "TRUCK"
	BARGE  PreCarriageUnderShippersResponsibility = "BARGE"
)

// All allowed values of PreCarriageUnderShippersResponsibility enum
var AllowedPreCarriageUnderShippersResponsibilityEnumValues = []PreCarriageUnderShippersResponsibility{
	"VESSEL",
	"RAIL",
	"TRUCK",
	"BARGE",
}

func (v *PreCarriageUnderShippersResponsibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PreCarriageUnderShippersResponsibility(value)
	for _, existing := range AllowedPreCarriageUnderShippersResponsibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PreCarriageUnderShippersResponsibility", value)
}

// NewPreCarriageUnderShippersResponsibilityFromValue returns a pointer to a valid PreCarriageUnderShippersResponsibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPreCarriageUnderShippersResponsibilityFromValue(v string) (*PreCarriageUnderShippersResponsibility, error) {
	ev := PreCarriageUnderShippersResponsibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PreCarriageUnderShippersResponsibility: valid values are %v", v, AllowedPreCarriageUnderShippersResponsibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PreCarriageUnderShippersResponsibility) IsValid() bool {
	for _, existing := range AllowedPreCarriageUnderShippersResponsibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to preCarriageUnderShippersResponsibility value
func (v PreCarriageUnderShippersResponsibility) Ptr() *PreCarriageUnderShippersResponsibility {
	return &v
}

type NullablePreCarriageUnderShippersResponsibility struct {
	value *PreCarriageUnderShippersResponsibility
	isSet bool
}

func (v NullablePreCarriageUnderShippersResponsibility) Get() *PreCarriageUnderShippersResponsibility {
	return v.value
}

func (v *NullablePreCarriageUnderShippersResponsibility) Set(val *PreCarriageUnderShippersResponsibility) {
	v.value = val
	v.isSet = true
}

func (v NullablePreCarriageUnderShippersResponsibility) IsSet() bool {
	return v.isSet
}

func (v *NullablePreCarriageUnderShippersResponsibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreCarriageUnderShippersResponsibility(val *PreCarriageUnderShippersResponsibility) *NullablePreCarriageUnderShippersResponsibility {
	return &NullablePreCarriageUnderShippersResponsibility{value: val, isSet: true}
}

func (v NullablePreCarriageUnderShippersResponsibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreCarriageUnderShippersResponsibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
